### ISSUE TITLE
Opt-in to Baffles using annotations

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/baffles-ui#22]
**Is your feature request related to a problem? Please describe.**
Ease adoption by simply labeling my deployment/pod/svc/etc... and Baffles discovers and displays it.

**Describe the solution you'd like**
I like the idea of a baffles standard that could be easily implemented in existing orchestration (think bigbang). IE if Baffles integration simply required that some resource (pod/service etc) could opt-in to baffles by adding annotation(s)..
If I were to deploy bigbang, I could easily add annotations to resources with extraAnnotations (for charts that were developed properly) and the baffles controller could pick those up.

**Comment by andrewsgreene** [comment]
thanks @brandtkeller

**Comment by andrewg-xyz** [comment]
Defer to https://github.com/defenseunicorns/pepr for auto creation of CRDs.
