### ISSUE TITLE
Possible Security Concern with Backend API

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/baffles-ui#55]
handler.go is open to possible path traversal

https://github.com/defenseunicorns/baffles-ui/pull/54/checks?check_run_id=11178096444

vite catches path traversal attempts with server.fs.strict set to true;

<img width="867" alt="Screenshot 2023-02-07 at 2 06 35 PM" src="https://user-images.githubusercontent.com/40547442/217366435-0bde3bc2-5d7c-4791-9b28-776fd44de02e.png">

If that is turned off you can access files outside of ./build/ui

<img width="790" alt="Screenshot 2023-02-07 at 2 06 09 PM" src="https://user-images.githubusercontent.com/40547442/217366520-e0192317-b4f2-47d2-a32d-0f9a4b711535.png">

https://vitejs.dev/config/server-options.html#server-fs-allow

**Vite controls this for local development, but is that check going to exist in PROD?**

**Comment by TristanHoladay** [comment]
In further looking into the handler, it appears a file system, locked down to the static built frontend directory, is created from which to serve files based on routes. From experimenting, as far as I can tell, there is no way for someone to use path traversal to access directories outside of the ./build/ui dir. Still want to double confirm this with @andrewg-xyz.

<img width="579" alt="Screenshot 2023-02-10 at 1 14 29 PM" src="https://user-images.githubusercontent.com/40547442/218189507-bddbf008-2a92-4275-8b33-91cdfa5dab2a.png">

**Comment by andrewg-xyz** [comment]
agree :) closing for now, can reopen if we discover otherwise
